# Generated by Django 2.1.5 on 2019-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(default='img/main_logo.jpg', upload_to='uploads'),
        ),
    ]
