# Generated by Django 2.1.5 on 2019-03-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190314_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=150, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='context',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.FileField(default='img/logo.jpg', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='img/logo.jpg', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='members',
            field=models.TextField(verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
    ]
