# Generated by Django 2.1.5 on 2019-03-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190315_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.TextField(verbose_name='Список')),
                ('total', models.IntegerField(verbose_name='Сумма')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contact', models.TextField(verbose_name='Контакты')),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='short',
            field=models.TextField(default='Подробности внутри', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Product', verbose_name='Продукт'),
        ),
    ]
